## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lastexam?useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Passw0rd
    
  ## JPA Properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
    ## Hibernate ddl auto (none, create, create-drop, validate, update)
    hibernate:
      ddl-auto: none